server:
  port: 8082

spring:
  application:
    name: task-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: taskmanager_tasks
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: task-service
    prefer-ip-address: true