server:
  port: 8083

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://mysql:3306/taskmanager_notifications?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: notification-service
    prefer-ip-address: true