server:
  port: 8084

spring:
  application:
    name: chat-service
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: chat-service
    prefer-ip-address: true