server:
  port: 8084

spring:
  application:
    name: chat-service
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key-here}
    url: https://api.openai.com/v1/chat/completions
    enabled: false  # Set to true when you have a valid OpenAI API key

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.taskmanager.chat: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.web.reactive: DEBUG